### ISSUE TITLE
relative excludes don't match as expected

### ISSUE THREAD

**Issue by stevenh** [CodeNarc/CodeNarc#755]
Using a pattern of `**/subdir/**` where `subdir` exists at the base directory doesn't exclude as expected. 

This test when added `src/test/groovy/org/codenarc/analyzer/FilesystemSourceAnalyzerTest.groovy` demonstrates the issue.
```groovy
    @Test
    void test_analyze_ExcludesBaseRelative() {
        analyzer.baseDirectory = BASE_DIR
        analyzer.includes = '**/*.groovy'
        analyzer.excludes = '**/subdir2/**'

        def results = analyzer.analyze(ruleSet)
        log("results=$results")

        def fullPaths = results.violations*.message
        assert fullPaths.containsAll([
            'src/test/resources/sourcewithdirs/SourceFile1.groovy',
            'src/test/resources/sourcewithdirs/subdir1/Subdir1File1.groovy',
            'src/test/resources/sourcewithdirs/subdir1/Subdir1File2.groovy'
        ])
        assert fullPaths.size() == 3

        assert testCountRule.count == 3
        assert results.getNumberOfFilesWithViolations(1) == 3
        assert results.totalNumberOfFiles == 3
    }
```

It actually results in the following files being validated from the base directory of `src/test/resources/sourcewithdirs`
```text
src/test/resources/sourcewithdirs/SourceFile1.groovy
src/test/resources/sourcewithdirs/subdir2/Subdir2File1.groovy
src/test/resources/sourcewithdirs/subdir2/subdir2a/Subdir2aFile1.groovy
src/test/resources/sourcewithdirs/subdir1/Subdir1File1.groovy
src/test/resources/sourcewithdirs/subdir1/Subdir1File2.groovy
```

All files in `subdir2` should have been excluded by `**/subdir/**` but they weren't.

This is fixed by https://github.com/CodeNarc/CodeNarc/pull/753 which was my original fix for https://github.com/CodeNarc/CodeNarc/issues/752

I know you were concerned about compatibility so went with https://github.com/CodeNarc/CodeNarc/pull/754 instead, but I think having the patterns behave how ant and hence users expect, given they are described as `ant like` in the documentation might be the best approach.

This can be validated by using the following file set with https://globster.xyz/
```text
SourceFile1.groovy
subdir2/Subdir2File1.groovy
subdir2/subdir2a/Subdir2aFile1.groovy
subdir2/subdir2b/NotAGroovyFile.txt
subdir1/Subdir1File1.groovy
subdir1/Subdir1File2.groovy
```

Now use the include `**/*.groovy` and exclude `**/subdir/**` patterns to show what should be matched and you see the following, where the files in blue are the ones which match:
![image](https://github.com/CodeNarc/CodeNarc/assets/104239/72e36d83-2bd7-4830-8ac8-f820b8cfa042)
![image](https://github.com/CodeNarc/CodeNarc/assets/104239/22d17e4f-1bae-4514-ba12-d146ccb42552)

**Comment by chrismair** [comment]
Wow, thanks very much for the detailed write up and explanation. That did indeed point out an error in the matching logic for includes + exludes. I committed a change to fix that, and again included the test that you provided.

I am not 100% opposed to pulling in your fix, but so far have not been convinced the extra complexity is necessary, although it certainly might be "better". I would be interested in tests for `WildcardPattern` that exposed the problems there. And/or other tests for the `FilesystemSourceAnalyzer` that exposed other issues.

Thanks.

**Comment by stevenh** [comment]
Awesome, thanks @chrismair for such a quick turn around much appreciated!

I can confirm using a build from current master allows me to get all tests passing now on `npm-groovy-lint` without errors, so if you could cut a release I can finish off https://github.com/nvuillam/npm-groovy-lint/pull/320, and work with @nvuillam to get a release of that and then vscode-groovy-lint too 😄 

You might well be right on the extra complexity, I'll have a dig some more once npm-groovy-lint and vscode-groovy-lint are all sorted.

**Comment by chrismair** [comment]
Thanks. The current timeframe for the next release was Jan/Feb. I'll see what I can do to condense that.

**Comment by stevenh** [comment]
This is still broken on Windows, investigating now, will post more details when I have it but pretty sure its going to be forward slash vs backslash somewhere.

**Comment by stevenh** [comment]
[PR to fix Windows is here](https://github.com/CodeNarc/CodeNarc/pull/756)

**Comment by chrismair** [comment]
CodeNarc version 3.4.0 has been released

**Comment by stevenh** [comment]
Thanks Chris!
